name: ModelSelector
version: '${project.version}'
main: fi.natroutter.modelselector.ModelSelector
api-version: 1.18
authors: [NATroutter]
description: Generates simple gui where you can take your custom models
website: https://NATroutter.fi
depend: [NATLibs]
libraries:
   - org.jsoup:jsoup:1.16.1
   - commons-io:commons-io:2.13.0