name: ModelSelector
version: '${project.version}'
main: fi.natroutter.modelselector.ModelSelector
api-version: 1.19
authors: [NATroutter]
description: Generates simple gui where you can take your custom models
website: https://NATroutter.fi
depend: [NATLibs]
libraries:
   - org.jsoup:jsoup:1.16.1
   - net.lingala.zip4j:zip4j:2.11.5